version: "3.9"
services:
    php-fpm:
        container_name: 'php-fpm-sskf'
        build:
            context: docker/php-fpm
        volumes:
            - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./:/app
        networks:
            statnet:

    php-cli:
        container_name: 'php-cli-sskf'
        build:
            context: docker/php-cli
        volumes:
            - ./:/app
        secrets:
            - host_ssh_key
        networks:
            statnet:

    redis:
        container_name: 'redis-sskf'
        image: redis:alpine
        ports:
            - ${REDIS_HOST_PORT}:${REDIS_PORT}
        command: redis-server --loglevel warning
        networks:
            statnet:

    chrome:
        container_name: 'chrome-sskf'
        image: selenium/standalone-chrome:latest
        ports:
            - "4444:4444"
        environment:
            SE_NODE_MAX_SESSIONS: 3
            SE_NODE_OVERRIDE_MAX_SESSIONS: true
        networks:
            statnet:
                ipv4_address: ${CHROME_IP}

#    db:
#        # in future versions add db settings
#        image: postgres:13.5-alpine
#        container_name: 'db-sskf'
#        volumes:
#            - ./docker/db/data.sql:/docker-entrypoint-initdb.d/dump.sql
#        ports:
#            - '5434:5432'
#        environment:
#            POSTGRES_DB: ${POSTGRES_DB}
#            POSTGRES_USER: ${POSTGRES_USER}
#            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#            POSTGRES_HOST_AUTH_METHOD: "trust"
#        networks:
#            statnet:

secrets:
    host_ssh_key:
        file: ${SSH_KEY}

networks:
    statnet:
        driver: bridge
        ipam:
            config:
                - subnet: 10.5.0.0/16
                  gateway: 10.5.0.1

